'use strict'

const DISCOVERY_PORT = 17654
const DISCOVERY_BROADCAST_ADDRESS = '255.255.255.255'
const PAIRING_CONTROL_PORT = 3000
const AGENT_ADMIN_PORT = 3001

module.exports = {
  DISCOVERY_BROADCAST_ADDRESS,
  DISCOVERY_PORT,
  PAIRING_CONTROL_PORT,
  AGENT_ADMIN_PORT,
}
