/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/transmission`; params?: Router.UnknownInputParams; } | { pathname: `/../types/temp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transmissionRecord` | `/transmissionRecord`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trustManagement` | `/trustManagement`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/transmission`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/temp`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/transmissionRecord` | `/transmissionRecord`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trustManagement` | `/trustManagement`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/transmission${`?${string}` | `#${string}` | ''}` | `/../types/temp${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/transmissionRecord${`?${string}` | `#${string}` | ''}` | `/transmissionRecord${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trustManagement${`?${string}` | `#${string}` | ''}` | `/trustManagement${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/transmission`; params?: Router.UnknownInputParams; } | { pathname: `/../types/temp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/transmissionRecord` | `/transmissionRecord`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trustManagement` | `/trustManagement`; params?: Router.UnknownInputParams; };
    }
  }
}
